title: dbic
description: 쿼리, 리눅스 명령어, DB 테이블 정의서 등 개인 문서 모음
url: https://mgar0717.github.io
baseurl: /dbic

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text

sass:
  style: compressed

# 상단 네비게이션
nav:
  - title: Home
    url: /
  - title: Queries
    url: /queries/
  - title: Linux
    url: /linux/

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - _config.local.yml
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
