title: dbic
description: 쿼리, 리눅스 명령어, DB 테이블 정의서 등 개인 문서 모음
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true
nav_sort: case_sensitive
heading_anchors: true

aux_links:
  "GitHub":
    - "https://github.com/mgar0717/dbic"

plugins:
  - jekyll-remote-theme
